version: '3'

services:
  app:
    build: .
    # command: bundle exec puma -C config/puma.rb
      command: bundle exec puma -C config/puma.rb -e production    
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    # depends_on:
    #   - db


  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pass
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_DATABASE: myapp_db
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
